### ISSUE TITLE
Ripping with UI introduces bad arguments

### ISSUE THREAD

**Issue by gregshep** [aztechian/ncodr#77]
When ripping a DVD with the UI, I enter {} in the option field.
The resulting command that is attempted in the docker container is `dvdbackup 0 { 1 } -M -p -v -n DOUBLESANYAGE_DDP -i /dev/sr0 -o /media/rips`  
If I log into the docker container and manually remove the `0 { 1 }` part, then the rip is successful.
Should  I remove the {} in the option field?

**Comment by aztechian** [comment]
Are you able to capture the log output from this job? It may be available with `docker logs <container>` or the `docker-compose` equivalent
